ocaml-wasm/wasm_of_ocaml

README.md
The little PR documents the current 'effect handler' setup, including the JSPI extension.
=> Document the JSPI extension too

README.md
I believe that Firefox 121 is no longer in beta.
=> Update Firefox version information in readme (no longer beta)

compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib/wasm/wa_code_generation.ml, compiler/lib/wasm/wa_core_target.ml, compiler/lib/wasm/wa_gc_target.ml, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_initialize_locals.ml, compiler/lib/wasm/wa_initialize_locals.mli, compiler/lib/wasm/wa_target_sig.ml, compiler/lib/wasm/wa_wat_output.ml
Ensure that locals are always explicitely initialized before being used.
=> Generate valid Wasm code

runtime/wasm/int64.wat
This factors out some code from `caml_int64_of_string` into a helper and exports it. It is used by o1-labs/integers_stubs_js#10 to have a parsing behavior consistent with the stdlib without duplicating too much code.
=> Export helper for i64 parsing

compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib/specialize_js.ml, compiler/lib/wasm/wa_gc_target.ml, runtime/wasm/runtime.js
When using functions such as `Js.Unsafe.eval_string` in Wasm, when the string is known at compile time, it can be emitted as an external Javascript fragment, rather than using the infamous `eval`.
=> Avoid using 'eval' for statically known strings

compiler/lib/wasm/wa_asm_output.ml, compiler/lib/wasm/wa_ast.ml, compiler/lib/wasm/wa_closure_conversion.ml, compiler/lib/wasm/wa_code_generation.ml, compiler/lib/wasm/wa_gc_target.ml, compiler/lib/wasm/wa_initialize_locals.ml, compiler/lib/wasm/wa_wat_output.ml
Currently in wasm, physical equality behaves differently from in Javascript: Javascript objects are boxed, and non-equality of the pointers causes the values to be physically not equal. This can be an issue for some folks who rely on the JS-object-inspecting semantics of physical equality to implement things such as memoizing.
This restores the fact that physical equality inspects Javascript objects. Other values are unaffected. This entails to pay an additional cost of between one and two Wasm runtime type tests in physical equality. A quick benchmark performing a few million `(==)` in an array of integers show a slowdown of 20~25 %. Since typical programs should perform physical equality much less frequently, we expect the overhead to be in the noise in practice.
That being said, we may …
=> Have physical equality inspect Javascript objects

compiler/lib/freevars.ml, compiler/lib/freevars.mli, compiler/lib/wasm/wa_code_generation.ml, compiler/lib/wasm/wa_code_generation.mli, compiler/lib/wasm/wa_curry.ml, compiler/lib/wasm/wa_gc_target.ml, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_globalize.ml, compiler/lib/wasm/wa_globalize.mli, compiler/lib/wasm/wa_structure.ml, compiler/lib/wasm/wa_structure.mli
Any variable which is used a number of instructions after being defined is stored into a global
instead of a local. The goals are the following:
- Turn a large number of closures into constant closures, which has a significant impact on performance
- Reduce the compilation time of the toplevel function in case the Wasm engine decide to optimize it: reduce the register pressure by avoiding long-lived registers in the toplevel function, and make load elimination less expensive by reducing the number of constant structures defined in this function.
This also improves binaryen's compilation time.
=> Store long-lived toplevel values into globals

compiler/bin-wasm_of_ocaml/cmd_arg.ml, compiler/bin-wasm_of_ocaml/cmd_arg.mli, compiler/bin-wasm_of_ocaml/compile.ml, compiler/bin-wasm_of_ocaml/dune, compiler/lib/driver.ml, compiler/lib/driver.mli, compiler/lib/generate.ml, compiler/lib/generate.mli, compiler/lib/link_js.ml, compiler/lib/source_map_io.mli, compiler/lib/source_map_io.yojson.ml, compiler/lib/wasm/wa_asm_output.ml, compiler/lib/wasm/wa_ast.ml, compiler/lib/wasm/wa_code_generation.ml, compiler/lib/wasm/wa_code_generation.mli, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_generate.mli, compiler/lib/wasm/wa_initialize_locals.ml, compiler/lib/wasm/wa_tail_call.ml, compiler/lib/wasm/wa_wat_output.ml, compiler/lib/wasm/wa_wat_output.mli, compiler/tests-jsoo/lib-effects/dune, compiler/tests-num/dune, compiler/tests-ocaml/lib-hashtbl/dune, compiler/tests-sourcemap/dune
Implement mapping between source and wasm locations.
To work, this requires a version of Binaryen compiled with Jérôme's patch WebAssembly/binaryen#6372, so I’m opening this a draft for now.
Single-stepping can jump around in slightly surprising ways in the OCaml code, due to the different order of operations in wasm. This could be improved by modifying Binaryen to support “no location” annotations. Another future improvement can be to support mapping Wasm identifiers to OCaml ones.
=> Sourcemap support for wasm

.github/workflows/build.yml, runtime/wasm/float.wat, runtime/wasm/jslib.wat, runtime/wasm/jsstring.wat, runtime/wasm/runtime.js, tools/node_wrapper.sh
https://github.com/WebAssembly/js-string-builtins
Enabled with flag --experimental-wasm-imported-strings in node, and through chrome://flags/#enable-experimental-webassembly-features in Chrome.
=> Use Js string builtins when available

compiler/tests-wasm_of_ocaml/dune, compiler/tests-wasm_of_ocaml/gh46.ml, runtime/wasm/compare.wat
The stack containing what remains to be compared was not resized
=> Fix comparison function

.github/workflows/build-wasm_of_ocaml.yml, README.md, runtime/wasm/dune
This allows us to use a stable version of Node.js.
=> Switch to Binaryen 118

runtime/wasm/effect.wat, runtime/wasm/obj.wat
With https://github.com/ocaml/ocaml/pull/12735, continuations should be implemented as a block with at least two fields.
We should port the optimization in that PR at some point to Js_of_ocaml and Wasm_of_ocaml.
=> Effects: make continuation format compatible with OCaml 5.2

runtime/wasm/bigarray.wat
The wasm implementation of `caml_ba_get_3` checks `j` twice instead of `j` and `k`.
=> Fix typo in `caml_ba_get_3` bounds check

examples/hyperbolic/hypertree.ml, lib/js_of_ocaml/dom_html.ml, lib/js_of_ocaml/dom_html.mli
This is part of the convergence work toward JSOO (see https://github.com/ocaml-wasm/wasm_of_ocaml/pull/57).
=> Integrate "added 'ellipse' method to canvasRenderingContext2D" (ocsigen/js_of_ocaml#1555)

compiler/lib/driver.ml, compiler/lib/effects.ml, compiler/lib/effects.mli, compiler/lib/generate.ml, compiler/lib/generate.mli
This makes the code clearer and will be helpful when rebasing ocsigen/js_of_ocaml#1461 after the merge of JSOO and WSOO.
=> Rename `cps_calls` into `trampolined_calls` for clarity

compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib/linker.ml, compiler/lib/linker.mli
And no longer ignore the always annotation, since this was only needed for `sys.js`.
=> Only link `jslib_js_of_ocaml` from the JavaScript runtime

.github/workflows/build-wasm_of_ocaml.yml, compiler/bin-wasm_of_ocaml/compile.ml, compiler/bin-wasm_of_ocaml/link.ml, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_generate.mli, compiler/lib/wasm/wa_link.ml, compiler/lib/wasm/wa_link.mli, compiler/lib/wasm/wa_source_map.ml, compiler/lib/wasm/wa_source_map.mli, compiler/lib/wasm/wa_wasm_link.ml, compiler/lib/wasm/wa_wasm_link.mli, compiler/lib/wasm/wa_wasm_output.ml, compiler/lib/wasm/wa_wasm_output.mli
- A single wasm file is generated for each cma archive, which avoid having to load too many module.
- Support linking wasmo files into one wasma file. One can do:
```
wasm_of_ocaml a.cmo
wasm_of_ocaml b.cmo
wasm_of_ocaml link -a -o foo.wasma a.wasmo b.wasmo
```
instead of:
```
ocamlc -a foo.cma a.cmo b.cmo
wasm_of_ocaml link -o foo.wasma foo.cma
```
This allows to make separate compilation more fine-grained, only regenerating Wasml code for modified files.
See https://github.com/ocaml/dune/pull/7389
=> Improved separate compilation

README.md
Separate compilation is now supported, as well as dynlink (I think?).
=> Update outdated info in readme

compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib/linker.ml, compiler/lib/linker.mli
We need it to get the primitive annotations.
This reverts #72. We will eventually use ocsigen/js_of_ocaml#1674.
=> Link the whole JavaScript runtime again

compiler/lib/code.ml, compiler/lib/code.mli, compiler/lib/deadcode.ml, compiler/lib/effects.ml, compiler/lib/eval.ml, compiler/lib/flow.ml, compiler/lib/freevars.ml, compiler/lib/generate.ml, compiler/lib/generate_closure.ml, compiler/lib/global_flow.ml, compiler/lib/inline.ml, compiler/lib/ocaml_compiler.ml, compiler/lib/parse_bytecode.ml, compiler/lib/phisimpl.ml, compiler/lib/specialize_js.ml, compiler/lib/subst.ml, compiler/lib/wasm/wa_core_target.ml, compiler/lib/wasm/wa_gc_target.ml, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_globalize.ml, compiler/lib/wasm/wa_liveness.ml, compiler/lib/wasm/wa_spilling.ml
This is part of the convergence work toward JSOO (see #57). ~~It is based on #67; the feature is contained in the last three commits.~~ edit: #67 has been merged.
It integrates the changes that occurred in number representation during the review of https://github.com/ocsigen/js_of_ocaml/pull/1649 and adapts wasm_of_ocaml in consequence.
=> Integrate latest changes to number representation from js_of_ocaml

runtime/wasm/runtime.js
> It's important to note that this will not reference the <script> element if the code in the script is being called as a callback or event handler; it will only reference the element while it's initially being processed.
https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript
Base was applied to the first wasm file, but not to subsequent files. This is an issue if you're loading a page at /foo/bar/baz and have your wasm hosted at /client.bc.wasm.assets, only appears in separate compilation.
=> Calculate fetchBase once at toplevel

runtime/wasm/runtime.js
I think the initial change in 90db9c5d997fe8130f3d1be81051615d4aa6f862 meant to use the static hasOwn but instead is calling on the object itself.
=> Use static Object.hasOwn

compiler/bin-wasm_of_ocaml/compile.ml, compiler/lib/wasm/wa_curry.ml, compiler/lib/wasm/wa_gc_target.ml, compiler/lib/wasm/wa_generate.ml, compiler/lib/wasm/wa_generate.mli, compiler/lib/wasm/wa_target_sig.ml, compiler/tests-wasm_of_ocaml/dune, compiler/tests-wasm_of_ocaml/gh107.ml
When one of the fields is not used, we fill it with the float value 0. rather than using the generic placeholder `(ref.i31 (i32.const 0))` , which does not make sense.
Fixes #107.
=> Fix bad interaction of deadcode elimination and unboxed float records

compiler/lib/wasm/wa_generate.ml, compiler/tests-wasm_of_ocaml/dune, compiler/tests-wasm_of_ocaml/gh112.ml, runtime/wasm/array.wat
=>  Fix creation of float arrays

compiler/lib-wasm/generate.ml, compiler/lib/flow.ml, compiler/lib/flow.mli, compiler/lib/specialize_js.ml
Some optimizations were no longer applied after the array initialization fix in https://github.com/ocaml-wasm/wasm_of_ocaml/pull/113. The following functions from `Js.Unsafe` were affected: `call`, `fun_call`, `meth_call` and `new_obj`.
The OCaml string is converted to a JavaScript string at compile time. This make us generate better code for the functions `Ojs.{get,set,delete}_prop_ascii` from gen_js_api.
=> Fix and improve the optimization of JavaScript interoperability primitives
